// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDX9CJVH6w7W6Sef5Tyavbpovzqc_V-iO8',
    appId: '1:170316411027:web:d108c7e98d0fe6a82e5d66',
    messagingSenderId: '170316411027',
    projectId: 'kalamy-basil-voice',
    authDomain: 'kalamy-basil-voice.firebaseapp.com',
    storageBucket: 'kalamy-basil-voice.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDX9CJVH6w7W6Sef5Tyavbpovzqc_V-iO8',
    appId: '1:170316411027:android:ANDROID_APP_ID',
    messagingSenderId: '170316411027',
    projectId: 'kalamy-basil-voice',
    storageBucket: 'kalamy-basil-voice.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDX9CJVH6w7W6Sef5Tyavbpovzqc_V-iO8',
    appId: '1:170316411027:ios:IOS_APP_ID',
    messagingSenderId: '170316411027',
    projectId: 'kalamy-basil-voice',
    storageBucket: 'kalamy-basil-voice.firebasestorage.app',
    iosBundleId: 'com.basilworld.kalamy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDX9CJVH6w7W6Sef5Tyavbpovzqc_V-iO8',
    appId: '1:170316411027:ios:IOS_APP_ID',
    messagingSenderId: '170316411027',
    projectId: 'kalamy-basil-voice',
    storageBucket: 'kalamy-basil-voice.firebasestorage.app',
    iosBundleId: 'com.basilworld.kalamy',
  );
}
